version: '2'
services:
  proxy:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile_proxy
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
  gen: 
    image: jwilder/docker-gen
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./tmp/templates:/etc/docker-gen/templates
    command: --notify-sighup proxy --watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
networks:
  default:
    external:
      name: nginx-proxy
